### ISSUE TITLE
Error: Unable to create log directory: Permission denied (os error 13)

### ISSUE THREAD

**Issue by Noxmore** [GoXLR-on-Linux/goxlr-utility#133]
I'm on Manjaro, I've tried installing goxlr-utility via the AUR (pamac with && without sudo), and extracting files directly from the RPM release, and every i try to run the .desktop file, goxlr-launcher, or goxlr-daemon, i get the error in the title, and nothing else.
Strangely, goxlr-client seems to work, but that won't be much use anyway without the daemon.

I'm not sure where it's trying to create the log directory, i had a quick peek in the code and couldn't find anything.
I have had problems with rust trying to make .rustup and .cargo in root, which i fixed by installing it without running pamac with sudo, but that had no effect here, help is much appreciated!

**Comment by FrostyCoolSlug** [comment]
If you're installing from AUR, on first run it should attempt to create a file in ~/.config/goxlr-utility/settings.json, and the other directories in `~/.local/share/goxlr-utility` (icons  logs  mic-profiles  presets  profiles  samples).

If you run goxlr-daemon from the command line, what output do you see?

**Comment by Noxmore** [comment]
I was running pamac as root, not the program

It matters not though, as it turns out `logs_directory` in `settings.json` was referencing the user of my previous Linux install! (I copied over most of my home directory to avoid re-configuring everything)

Thank you much for your help, and with that, i pronounce this issue CLOSED

**Comment by FrostyCoolSlug** [comment]
Great, glad that's fixed.

As a heads up, the util tries to use the `$XDG_DATA_HOME` environment variable (and if not present `$HOME`) to determine where it should be dropping files, if it's not set correctly you may run into similar issues with other apps. It's probably wise to run `env` and confirm that the settings are correct, if not it would be wise to fix them, otherwise you may run into issues with over applications!

Enjoy!
