### ISSUE TITLE
The UI won't open

### ISSUE THREAD

**Issue by markusradmark** [GoXLR-on-Linux/goxlr-utility#137]
I installed the driver and the GoXLR Utility and it's running. But when I press configure GoXLR the UI window doesn't show.
Do anyone have a fix for this?

**Comment by JulanDeAlb** [comment]
Hey, can you check if you can access the UI via http://localhost:14564

**Comment by JulanDeAlb** [comment]
Can you try downloading and installing [WebView2](https://go.microsoft.com/fwlink/p/?LinkId=2124703) and give it another try?
Normally the installer tries to download it, but lately we had several reports that it didn't download correctly.

**Comment by markusradmark** [comment]
For some reason it just works a few days later, used the localhost page until now.

**Comment by TeamWolfyta** [comment]
Also getting this on version 1.0.3, Refuses to launch the UI when running "C:\Program Files\GoXLR Utility\goxlr-launcher.exe" but will launch the UI when running "C:\Program Files\GoXLR Utility\goxlr-utility-ui.exe"

**Comment by FrostyCoolSlug** [comment]
> Also getting this on version 1.0.3, Refuses to launch the UI when running "C:\Program Files\GoXLR Utility\goxlr-launcher.exe" but will launch the UI when running "C:\Program Files\GoXLR Utility\goxlr-utility-ui.exe".

Does the webui start instead when you run the launcher?

Could you also confirm what happens when you click the tray icon when the Daemon is running?

**Comment by TeamWolfyta** [comment]
@FrostyCoolSlug It doesn't launch when executing via "goxlr-launcher.exe" but it will work when executing "goxlr-utility-ui.exe". Also there no icon tray icon but according to task manager, the daemon is running in the background.

**Comment by FrostyCoolSlug** [comment]
Does the webui work? ( You should be able to open http://localhost:14564 n a web browser)? It sounds like the utility just isn't launching properly.

**Comment by FrostyCoolSlug** [comment]
Also, could you provide me with the log files, in the UI, you should be able to go to system -> Settings and click the folder icon next to the log level.

**Comment by TeamWolfyta** [comment]
@FrostyCoolSlug I did some basic debugging before commenting on this issue and back then the web server was working, Just checked again now to confirm that yup, web server still working.

Sure here are the logs: [goxlr-daemon.log](https://github.com/GoXLR-on-Linux/goxlr-utility/files/13802099/goxlr-daemon.log). If you require any other kinds of logs just say and I'll try and get them for you.

Just to note I closed anything GoXLR related in task manager and deleted the logs so it would be as close to me powering on my PC as possible, To me the logs don't give much to go off of so I did a bit of playing around and noticed somethings: 

- Once starting up GoXLR Utility for the first time everything worked normally, The daemon started and the UI launched. 
- Upon closing the UI and trying to reopen, it would just hang and not do anything other than throw an error in the log.
- While the UI was open in task manager a process name by the name "GoXLR Utility" was running, Once closing the UI that same process would just stay there as if it's still running, I'm not sure what that process does but if it's supposed to be the UI then the UI shouldn't be open because I just closed it, If it's supposed to be a taskbar icon then I don't have one.

Tried changing the log level and replicating the same things I did when playing around with it and it just logs the same thing and doesn't seem to provide anything helpful. The daemon is still running through all of this mind you so maybe it's failing to properly recognize that the daemon is still running?

**Comment by FrostyCoolSlug** [comment]
Thanks, I'll do some additional testing on this..

The UI is supposed to stay open, but hidden, if you close it. It's runtime is bound to the daemon so if the utility is shutdown the UI will close along with it. The reasoning behind this is that it takes several seconds to run the UI up from cold, so we just keep it in the background staying warm until it's needed again.

Looking at the logs is kinda interesting though, the `goxlr-launcher` binary is supposed to determine whether the daemon is running or not, if it's not running launch it, if it's running activate the UI. The errors in the log files imply it's attempting to start the daemon even though it's already running (which is why the UI isn't popping up), someone else has reported this recently on discord, so I'll need to find out what's going on there.

Thanks for the close analysis, it's certainly help with tracking down where things are going wrong!

**Comment by FrostyCoolSlug** [comment]
Can you give the Windows artifact on the bottom of this https://github.com/GoXLR-on-Linux/goxlr-utility/actions/runs/7436762911 action an install, and let me know if it solves the problem?

Thanks.

**Comment by TeamWolfyta** [comment]
Can confirm that trying to re-launch the UI using "C:\Program Files\GoXLR Utility\goxlr-launcher.exe" now works. Also works when launching via the system tray icon (I thought the system tray icon was broken too but just noticed there is a setting for it, Had it off the entire time, Just turned it on and the system tray icon also launches it, I'm just slightly blind 😆)

Thanks for fixing this issue!
