### ISSUE TITLE
.goxlrProfile "Couldn't read profile"

### ISSUE THREAD

**Issue by lm41** [GoXLR-on-Linux/goxlr-utility#18]
#### Profile file: test1.goxlrProfile
```
./goxlr-client profiles device load test1
Error: Unable to Load Profile

Caused by:
    Couldn't read profile
```
#### Here the profile:
[test1.zip](https://github.com/GoXLR-on-Linux/goxlr-utility/files/9038995/test1.zip)

The issue could be caused by the sampler files in the goxlrProfile file.

**Comment by FrostyCoolSlug** [comment]
Can you let me know the app version on Windows, (and firmware please)?

**Comment by FrostyCoolSlug** [comment]
Out of interest, how was this profile generated? It contains a regular .goxlr profile inside it (which can be loaded by the daemon), as well as various samples and scribbles..

**Comment by lm41** [comment]
> Out of interest, how was this profile generated? It contains a regular .goxlr profile inside it (which can be loaded by the daemon), as well as various samples and scribbles..

I created the profile like any other. 
New profile -> Personalize -> Save

##### But I think it's actually good if the samples are saved directly in the profile. Can you play samples directly from a .zip file?

**Comment by FrostyCoolSlug** [comment]
Interesting, that would imply the windows app has two different 'types' of profile.. if you load a default profile, change and save, it only produces a .goxlr file, but if you create a new profile it generates a .goxlrProfile file, and handles saving differently.

I'll need to review how that works internally on Windows before supporting the format, shouldn't be too difficult:)

**Comment by FrostyCoolSlug** [comment]
Did some checking and from what I can tell, that's a very old version of the windows app (latest is 1.4.34.205).

More recent versions of the GoXLR App under windows don't support the .goxlrProfile format (I wasn't able to get that profile to load at all). So for now I'm going to keep this relatively low priority. I think the most 'support' I'm going to introduce into the daemon is to simply extract the parts of the profile into their respective locations.

**Comment by FrostyCoolSlug** [comment]
For now, I'm going to close this as 'WONTFIX'. The more I look at it, the more problems I start to see. The utility was developed long after the .goxlrProfile format was removed from the Windows App, so we'd be adding support for old and deprecated functionality.. In addition, I'm not sure the actual .goxlr profile embedded in the file is fully compatible with our parser as it's an older version (the parser was built for v3 profiles, with limited support for v2, which this is). 

The best bet for this kind of profile would be to simply open them in a zip viewing program, extracting it's contents to the correct place and seeing if it loads.. Otherwise we'll just be running backwards trying to support things that TC-Helicon don't even support anymore!

With that said, if someone wants to support it, I'll certainly review and accept a PR for it!
