### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by delinx** [GoXLR-on-Linux/goxlr-utility#28]
Hey, just wanted to **say thank you** from the bottom of my heart, I have to unplug goxlr every night cause of lights (not all can be turned off with software, like inner LED and rotatory things white mark), and every time before booting into linux for some work I had to boot into windows first to wake it up. 

Now I can stop myself from booting into windows where all of my distractions live...

There is so much effort which went into this, really thank you for doing such an amazing job!

_Shame on **TC Helicon** for making this so much harder then it has to be. Some specs released would of been at least an attempt of giving the community a chance._

**Comment by FrostyCoolSlug** [comment]
Thanks for the kind words :)

Just to note on the last paragraph, this project has had a relationship with TC-Helicon since the early days of the Utility, while 99.9% of the protocol was derived via reverse engineering, we've been provided with data and information which has allowed us to verify (and in some places tweak) structures and calculations to ensure the behaviour is consistent, and things work as expected. They've also been incredibly willing to help answer questions about behaviours (for example, the EQ calculations on the full device wouldn't have been possible without them). When it's all said and done, I don't think this project would have come as far as it has without them!
