### ISSUE TITLE
Unknown output on start/restart of audio stream

### ISSUE THREAD

**Issue by APN-Faulty** [GoXLR-on-Linux/goxlr-utility#36]
As of version 0.5.0 when an audio stream is started or restarted the audio output of the application is set to unknown. 
Changing it manually allows it to work temporarily until the audio stream is restarted. 
Issue doesn't exist in 0.4.0 after downgrading
Popos 22.04 (latest updates) using alsa

**Comment by FrostyCoolSlug** [comment]
Odd, the utility doesn't actually interact with the audio components of the OS, so this is a little strange..

Can you run the util with `--log-level debug` and see if it's throwing any errors?

Thanks

**Comment by APN-Faulty** [comment]
Just reinstalled 0.5.0 and im not having the issue now which is strange. when i was having the issue i tried killing and restarting the daemon, replugging the goxlr and rebooting the system yet it was persistant. now im not getting the problem at all.
i have noticed though that when i was having the issue it was creating multiple audio streams eg. when watching youtube there would be 2 chromium streams, one with the correct output and the other with unknown output which was causing the video/audio playback to freeze until set to the correct output.
Its extremely odd since i haven't changed anything on my system in the last 24 hours apart from downgrading to 0.4.0

**Comment by FrostyCoolSlug** [comment]
That is indeed odd, is it possible a glitched version of Chromium slipped in, then was quickly reverted?

The utility itself doesn't interact in any way with audio streams, it's simply an implementation of the 'vendor' interface on the GoXLR, handling things like colours, buttons, the internal routing table and mixers etc. Actual audio and stream handling happens via ALSA and the Linux Kernel, which would certainly make this a little tricker to diagnose, because the problem you seem to be experiencing lie in that area.. 

Given everything is working properly again, are you happy to flag this as resolved? And if it occurs again, we can possibly look a little deeper?

Thanks,
Craig
