### ISSUE TITLE
Reloading Profile does not Reset Effects

### ISSUE THREAD

**Issue by hllf** [GoXLR-on-Linux/goxlr-utility#63]
When you reload a profile, either via the UI or CLI, the effects appear to remain as they were, rather than being reset back to what is saved in the profile. To reproduce:

1. Start the daemon.
2. Turn on effects, select a preset, turn knobs to make changes.
3. Reload the profile via the UI or by typing "goxlr-client profile device load <name>"
4. You will see the effects remain on, and they are not reset back to the profile's settings.

If you stop and restart the daemon, however, the effects turn off, and everything is reset back to the profile's saved settings correctly.

The expected behavior for realoding a profile should mirror that of restarting the daemon exactly. Every setting saved in the profile should be re-applied.

**Comment by FrostyCoolSlug** [comment]
Thanks for the report,

I've got a tentative fix for this in the 0.12 branch, the problem was caused because the FX panel settings are strictly speaking 'Mic Effects' and fall into the same GoXLR command as things like Gate / Compressor / EQ, so it made sense to apply them all at once. 

Obviously, that's bad, because it resulted in them only being applied during mic profile load. I've split them out so FX and setting should load with the profile now.

Could you give it a test please?

**Comment by hllf** [comment]
I've ran a few tests, and it works perfectly now!

I'll let you know if I see anything else as I test more.

Thank you!

**Comment by FrostyCoolSlug** [comment]
Are you happy to close this one up now? Lemme know if you've experienced other problems.

**Comment by hllf** [comment]
Nope it's all good, I'll close it.
