### ISSUE TITLE
[BUG] Get Driver API library from registry

### ISSUE THREAD

**Issue by FrostyCoolSlug** [GoXLR-on-Linux/goxlr-utility#89]
Currently the path to the driver is hard coded in [tusbaudio.rs](https://github.com/GoXLR-on-Linux/goxlr-utility/blob/f2a5c1b22080c7cfb2a096efde23913a149b657a/usb/src/device/tusb/tusbaudio.rs#L38C23-L38C23) which prevents the utility from launching on systems which don't use the standard path names.

Check how the official app locates the driver API file and attempt to replicate, otherwise search the registry for the install path.

**Comment by lm41** [comment]
Windows uses always the english pathnames. Everything else is just the look. 
![Screenshot (121)](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/59062169/0336390a-b6f6-443d-9079-208cdb6e00ac)
![Screenshot (120)](https://github.com/GoXLR-on-Linux/goxlr-utility/assets/59062169/246944b1-c6bb-46c1-b802-703ead556502)

Maybe the problem is that the driver is not installed in the default location?

**Comment by devHazz** [comment]
From what I've seen so far, the path is queried from an InprocServer32 reg key which I'm guessing is set on install based on the executable path? Seems it may just be as simple as pointing to the default directory?

**Comment by FrostyCoolSlug** [comment]
Good shout, the queried path is HKCR\WOW6432Node\CLSID\{024D0372-641F-4B7B-8140-F4DFE458C982}\InprocServer32\ when the official app starts.

Had to change that slightly because we're a 64bit app, (remove the WOW6432Node component), but the util will now check there first as of 2a8d818c then fall back to the default path if it's missing.

**Comment by FrostyCoolSlug** [comment]
This has been released as part of 0.12.3 in commits 1add5d8, 2a8d818 and 6a8f116
